services:
  - type: web
    name: pulsechat-studio
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        value: Karan Singh
      - key: ADMIN_PASSWORD
        value: Rajput2007
